cuda_compiler_version:       # [(linux or win)]
  - 12.8                     # [((linux and x86_64) or win)]
  - 13.0                     # [(linux or win)]
gpu_variant:
  - cuda                     # [(linux or win)]
