{% set version = "0.8.2" %}
{% set number = 0 %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: torchvision-split
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 9a866c3c8feb23b3221ce261e6153fc65a98ce9ceaa71ccad017016945c178bf
  patches:
    # skip failing test thats already marked as flaky upstream, see
    # https://github.com/pytorch/vision/blob/v0.8.2/test/test_models.py#L90
    - patches/0001-skip-flaky-test.patch

build:
  number: {{ number }}
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('cxx') }}

outputs:
  - name: torchvision
    script: build-torch.sh   # [not win]
    script: build-torch.bat  # [win]
    build:
      string: "h{{ PKG_HASH }}_{{ number }}_{{ torch_proc_type }}"                                                  # [cuda_compiler_version == "None"]
      string: "cuda{{ cuda_compiler_version|replace(".", "") }}h{{ PKG_HASH }}_{{ number }}_{{ torch_proc_type }}"  # [cuda_compiler_version != "None"]
      run_exports:
        # ensure matching proc-type
        - torchvision =*=*_{{ torch_proc_type }}

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}         # [cuda_compiler_version != "None"]
      host:
        - python
        - pip
        - setuptools
        - cudnn                          # [cuda_compiler_version != "None"]
        # split off image/video into separate outputs?
        - jpeg
        - libpng
        # ffmpeg
        - numpy
        - pillow >=4.1.1
        - pytorch =*={{ torch_proc_type }}*
      run:
        - python
        - pytorch =*={{ torch_proc_type }}*
        - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != "None"]
        - {{ pin_compatible('numpy') }}
        - pillow >=4.1.1

    test:
      requires:
        - pytest
        - scipy
      source_files:
        - test
      imports:
        - torchvision
        - torchvision.datasets
        - torchvision.models
        - torchvision.transforms
        - torchvision.utils
      commands:
        - pytest test/

  # for compatibility with (& ease of migration from) old packages in the pytorch channel, see
  # https://anaconda.org/pytorch/torchvision-cpu/files
  - name: torchvision-cpu
    build:
      skip: true  # [cuda_compiler_version != "None"]
    requirements:
      run:
        - torchvision ={{ version }}=*_cpu
    test:
      imports:
        - torchvision

about:
  home: http://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - nehaljwani
    - hmaarrfk
    - h-vetinari
  feedstock-name: torchvision
