{% set version = "0.8.2" %}

package:
  name: torchvision
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 9a866c3c8feb23b3221ce261e6153fc65a98ce9ceaa71ccad017016945c178bf

build:
  number: 0
  skip: True  # [not (osx or linux64)]
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [pytorch_variant == "gpu"]
  string: cpu_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}                                      # [pytorch_variant == "cpu"]
  script:
    - export NVCC_FLAGS="-ccbin ${CC}"
    - export FORCE_CUDA=0  # [pytorch_variant != "gpu"]
    - LDFLAGS="${LDFLAGS//-Wl,-z,now/-Wl,-z,lazy}"
    - export TORCHVISION_INCLUDE="${PREFIX}/include"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*  # [pytorch_variant == "gpu"]
    # other requirements
    - python
    - pip
    - setuptools
    - jpeg
    - libpng
    - pytorch 1.7.1  # [not s390x]
    - pytorch 1.8.1  # [s390x]
  run:
    - _pytorch_select ==0.1             # [pytorch_variant == "cpu"]
    - _pytorch_select ==0.2             # [pytorch_variant == "gpu"]
    # GPU requirements
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [pytorch_variant == "gpu"]
    # other requirements
    - python
    - pillow >=4.1.1
    - numpy >=1.11
    - pytorch 1.7.1  # [not s390x]
    - pytorch 1.8.1  # [s390x]
    - six

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
    - torchvision.models
    - torchvision.utils
  source_files:
    - test
  requires:
    - pytest
    - scipy
    - mock  # [linux]
    - requests
  commands:
    pytest . -k "not video" -k "not test_url_is_accessible"

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - katietz
    - jjhelmus
    - nehaljwani
