{% set version = "0.15.2" %}

package:
  name: torchvision
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 1efcb80e0a6e42c54f07ee16167839b4d302aeeecc12839cc47c74b06a2c20d4

build:
  number: 0
  skip: True  # [py<37 or s390x or ppc64le]
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [pytorch_variant == "gpu"]
  string: cpu_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}                                      # [pytorch_variant == "cpu"]
  script:
    - export NVCC_FLAGS="-ccbin ${CC}"  # [not win]
    - set FORCE_CUDA=0  # [win and (pytorch_variant != "gpu")]
    - export FORCE_CUDA=0  # [not win and (pytorch_variant != "gpu")]
    - LDFLAGS="${LDFLAGS//-Wl,-z,now/-Wl,-z,lazy}"    # [not win]
    - set "TORCHVISION_INCLUDE=%LIBRARY_INC%"         # [win]
    - export TORCHVISION_INCLUDE="${PREFIX}/include"  # [not win]
    - "{{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation"
  missing_dso_whitelist:
    - "$RPATH/libc10.so"           # [linux]
    - "$RPATH/libc10.dylib"        # [osx]
    - "$RPATH/libtorch_cpu.so"     # [linux]
    - "$RPATH/libtorch_cpu.dylib"  # [osx]
    - "$RPATH/libc10.so"           # [linux]
    - "$RPATH/libc10.dylib"        # [osx]
    - "$RPATH/c10.dll"             # [win]
    - "$RPATH/torch_cpu.dll"       # [win] 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # libpng and libjpeg must be available at compilation time in order to be available,
    # see https://github.com/pytorch/vision/tree/v0.11.3#image-backend
    - jpeg      # [not win]
    - libpng
  host:
    - python
    - pip
    - wheel
    - numpy {{ numpy }}
    - pytorch 2.0.1
    # libpng and libjpeg must be available at compilation time
    - jpeg {{ jpeg }}  # [not win]
    - libpng {{ libpng }}
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}  # [pytorch_variant == "gpu"]
    # 2022/08/25: Not requiring ffmpeg because torchvision has bugs with certain ffmpeg versions, 
    # see https://github.com/pytorch/vision/issues/5419#issuecomment-1193483864
    # and https://github.com/conda-forge/torchvision-feedstock/commit/4ec4b5f4eb4889dbb1f8da34662ea622bb4b3828
    # - ffmpeg
  run:
    # GPU requirements
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [pytorch_variant == "gpu"]
    - {{ pin_compatible('numpy') }}
    - python
    - pillow >=5.3.0,!=8.3.*
    - pytorch
    - requests
    - jpeg  # [not win]
    - libpng
    - setuptools
    # - ffmpeg

# Skip test_url_is_accessible instead of hitting 20+ servers per run, since
# each server might be occasionally unresponsive and end up failing our CI
{% set tests_to_skip = "test_url_is_accessible" %}

# 2022/08/30: Skipping the av tests (they require module 'av'): ModuleNotFoundError: No module named 'av',
# because the av package depends on ffmpeg, which we are not requiring as a run requirement because torchvision has bugs with certain ffmpeg versions.
{% set tests_to_skip = tests_to_skip + " or test_classes or test_feature_types or test_feature_types or test_is_valid_file or test_num_examples or test_smoke or test_str_smoke or test_transforms" %}
# 2022/08/30: AssertionError: Tensor-likes are not equal!
#{% set tests_to_skip = tests_to_skip + " or test_adjust_gamma" %}
# 2022/08/30: This test seems to just destroy the memory of the system.
# they actually run on most platform except but were still hanging on linux-aarch64 and osx-arm64
{% set tests_to_skip = tests_to_skip + " or test_forward_backward" %}
{% set tests_to_skip = tests_to_skip + " or test_jit_forward_backward" %}
# 2023/07/06: CIs do not have enough resources to run the full suite of model tests
# test_extended_models
{% set tests_to_skip = tests_to_skip + " or test_get_model or test_get_model_builder or test_get_model_weights" %}
{% set tests_to_skip = tests_to_skip + " or test_weights_copyable or test_weights_deserializable or test_list_models" %}
{% set tests_to_skip = tests_to_skip + " or test_get_weight or test_naming_conventions or test_schema_meta_validation" %}
# from now on something surely needs to be disabled
{% set tests_to_skip = tests_to_skip + " or test_transforms_jit or test_no_warn or test_pretrained_pos" %}
{% set tests_to_skip = tests_to_skip + " or test_pretrained_kw or test_equivalent_behavior_weights" %}
{% set tests_to_skip = tests_to_skip + " or test_multi_params or test_default_callable or test_pretrained_deprecation" %}
# test_models
{% set tests_to_skip = tests_to_skip + " or test_detection_model" %}
{% set tests_to_skip = tests_to_skip + " or test_quantized_classification_model" %}  # [linux]

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
    - torchvision.models
    - torchvision.utils
  source_files:
    - test
    - references
  requires:
    - pip
    - pytest
    - pytest-mock
    - scipy
    # For pkg_resources
    - setuptools
  commands:
    - pip check || true      # [not win]
    - pip check || (exit 1)  # [win]
    - pytest -v -k "not ({{ tests_to_skip }})" test/  # [(osx and arm64)]
    - pytest -v -k "not ({{ tests_to_skip }} or test_frozenbatchnorm2d_eps)" test/  # [linux and aarch64]
    - pytest -v -k "not ({{ tests_to_skip }} or test_maskrcnn_resnet50_fpn_cpu)" test/  # [linux and (not aarch64)]

about:
  home: https://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  description: |
    The torchvision package consists of popular datasets, model architectures, and common image transformations for computer vision.
  dev_url: https://github.com/pytorch/vision
  doc_url: https://pytorch.org/docs/stable/index.html

extra:
  recipe-maintainers:
    - katietz
    - jjhelmus
    - nehaljwani
  skip-lints:
    - python_build_tool_in_run