{% set version = "0.3.0" %}

package:
  name: torchvision
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: c205f0618c268c6ed2f8abb869ef6eb83e5339c1336c243ad321a2f2a85195f0

build:
  number: 1000
  skip: True  # [not linux64]
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}
  script:
    - export NVCC_FLAGS="-ccbin ${CC}"
    - LDFLAGS="${LDFLAGS//-Wl,-z,now/-Wl,-z,lazy}"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*
    # other requirements
    - python
    - pip
    - pytorch >=1.1.0
    - future  # [py2k]
  run:
    # GPU requirements
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    # other requirements
    - python
    - pillow >=4.1.1
    - numpy >1.11
    - pytorch >=1.1.0
    - six
    - future  # [py2k]

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  source_files:
    - test
  requires:
    - pytest
    - scipy
  commands:   # [not py==36]
    pytest .  # [not py==36]

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
