{% set version = "0.8.2" %}

package:
  name: torchvision
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: 9a866c3c8feb23b3221ce261e6153fc65a98ce9ceaa71ccad017016945c178bf

build:
  number: 0
  skip: true  # [not linux64]
  script: |
    export TORCHVISION_INCLUDE=$PREFIX/include/  # [not win]
    set TORCHVISION_INCLUDE=%LIBRARY_INC%        # [win]
    {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    # split off image/video into separate outputs?
    - libjpeg-turbo
    - libpng
    # ffmpeg
    - numpy
    - pillow >=4.1.1
    - pytorch
  run:
    - python
    - pytorch
    - {{ pin_compatible('numpy') }}
    - pillow >=4.1.1

test:
  requires:
    - pytest
    - scipy
  source_files:
    - test
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.models
    - torchvision.transforms
    - torchvision.utils
  commands:
    - pytest test/

about:
  home: http://pytorch.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - nehaljwani
