{% set version = "0.4.0" %}

package:
  name: torchvision
  version: {{ version }}

source:
  fn: torchvision-{{ version }}.tar.gz
  url: https://github.com/pytorch/vision/archive/v{{ version }}.tar.gz
  sha256: c270d74e568bad4559fed4544f6dd1e22e2eb1c60b088e04a5bd5787c4150589

build:
  number: 1000
  skip: True  # [not linux64]
  string: cuda{{ cudatoolkit | replace('.', '') }}py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}  # [pytorch_variant == "gpu"]
  string: cpu_py{{ CONDA_PY }}h{{PKG_HASH}}_{{ PKG_BUILDNUM }}                                      # [pytorch_variant == "cpu"]
  script:
    - export NVCC_FLAGS="-ccbin ${CC}"
    - LDFLAGS="${LDFLAGS//-Wl,-z,now/-Wl,-z,lazy}"
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    # GPU requirements
    - cudatoolkit {{ cudatoolkit }}*
    # other requirements
    - python
    - pip
    - pytorch 1.2.0
    - future  # [py2k]
  run:
    # GPU requirements
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}
    # other requirements
    - python
    - pillow >=4.1.1
    - numpy >1.11
    - pytorch 1.2.0
    - six
    - future  # [py2k]

test:
  imports:
    - torchvision
    - torchvision.datasets
    - torchvision.transforms
  source_files:
    - test
  requires:
    - pytest
    - scipy
    - mock
  commands:
    pytest . -k "not video"

about:
  home: http://pytorch.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Image and video datasets and models for torch deep learning
  dev_url: https://github.com/pytorch/vision
  doc_url: http://pytorch.org/docs/master/torchvision

extra:
  recipe-maintainers:
    - jjhelmus
    - nehaljwani
