travis:
  secure:
    BINSTAR_TOKEN: mriRLa9MDoPbwz+ecQ5AStAET59XDxH19LgD1YQuiw/3iFd/bnI2Q3EscPykV7t79gj4yqBnO6vk91owPCQweSBLgNex9dDb71xrKEHE/0yY5MkS+YTlh7AUioyPcIESllicFd6Rj6UPhWGUVyXQtyIjmneTMOPyWB2Zn1dF72nPtoq9f0iyrNo1mxSlVqS7o53CbfR+8+cha4T3SfPblPv4g9Qb7lbLuzETzu6GdfDjVVPV9UpVCySwgi0fBqUTo5OPpPnWDtKtMYmXckDjEzo5fRyg2LsDBtOfIn2MMpJeu+sCr6t87w3aB6g0awTmzdXlSvd+AuxkXjq7lxb8kq9HPStRZxNQwrR54iztrPjp06LTENeZ4wxRHn+mbWzOwCOv9SvOTQTWEWt/QhtYAvMF49+J7I0WnKeuwlW6jLihzmr0G2WVkO5ZVDDOvsdiqpckjyjeKnjQbNj99ooHTQbvkRTXJji3j5m5kMWzn1StZIRajWwpTyD+wsIpDV6nY/D7QnrKhmdNbWgq52aQscrVUCjnpzDavu2BUztWLM0i73/bsZ8SwfUG1OlX6Y+UfNgc2ILZ7p6a458V0S/10mVnvoSHxki7Op8hTFuKa22tIoAzC0COctBuyNZInYp9z9Q7NdcIYvgtVJ2jzqWB0RGTgjDtUog/iCwe9CstZ9g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
